export enum MessageType {
  HANDSHAKE_INIT = 0x01,
  HANDSHAKE_RESPONSE = 0x02,
  RPC_CALL = 0x10,
  RPC_RESPONSE = 0x11,
  RPC_ERROR = 0x12,
  SUBSCRIBE = 0x20,
  EVENT = 0x21,
  HEARTBEAT = 0x30,
  CLOSE = 0xff
}

export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  INVALID_REQUEST = 'INVALID_REQUEST',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  TIMEOUT = 'TIMEOUT',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  DECRYPTION_FAILED = 'DECRYPTION_FAILED',
  INVALID_NONCE = 'INVALID_NONCE'
}
